Sets SUBLIMEREPL_DIR with unicode path
Sets SUBLIMEREPL_DIR with a Unicode object representing
the current working directory.

The problem occures on Windows, when the path to SublimeREPL package folder contains non ASCII characters,
and when we want through Command Pallete (Ctrl+Shift+P) select the approperiate language to open REPL.
Error:
	Traceback (most recent call last):
	File ".\sublime_plugin.py", line 337, in run_
	File ".\run_existing_command.py", line 31, in run
	File ".\ntpath.py", line 108, in join
	UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 9: ordinal not in range(128)

In run_existing_command.py file, SUBLIMEREPL_DIR has been set by
os.getcwd() which returns a string representing the current working directory.
Solution to the problem is to return unicode object - os.getcwdu().